trajectory_execution:
  allowed_execution_duration_scaling: 3.0  # Concede il doppio del tempo stimato per finire
  allowed_goal_duration_margin: 1        # Concede 0.5s extra alla fine
  allowed_start_tolerance: 1          # Aumentato a 10% (era 0.05)
  execution_duration_monitoring: false  # <--- QUESTA Ãˆ LA CHIAVE! SPEGNI IL CRONOMETRO
  wait_for_trajectory_completion: true